/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Datos;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author java
 */
public class Cuentas extends javax.swing.JFrame {

    /**
     * Creates new form Cuentas
     */
    private Statement sentenciaSQL;
    private ResultSet rs;
    conexion cnn;
    datosc aux;
    public Cuentas() {
        initComponents();
        MostrarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Busqueda = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        articulo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre del Cliente:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        jPanel1.add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 350, -1));

        Busqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Busqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BusquedaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Busqueda);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 600, 140));

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Buscar Cliente");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jTabbedPane1.addTab("Cuentas del cliente", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Articulo:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 220, -1));

        articulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        articulo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                articuloPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(articulo);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 580, 140));

        jTabbedPane1.addTab("Articulos", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 630, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void envia(){
        Clientes cl=new Clientes();
        cl.numero.setText(aux.cliente());
        cl.nombre.setText(aux.nom());
        cl.paterno.setText(aux.paterno());
        cl.materno.setText(aux.materno());
        cl.direccion.setText(aux.direccion());
        cl.Telefono.setText(aux.telefono());
        cl.show();
    }
    private void BusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BusquedaMouseClicked
        // TODO add your handling code here:
         if(evt.getButton()==1){
            int fila=Busqueda.getSelectedRow();
            //sentenciaSQL.executeUpdate("INSERT INTO alumnos (id_Alumnos,Nombre,Apellido,Curso,Titulacion) VALUES ("+Integer.parseInt(txtidalumno.getText())+",'"+txtalumno.getText()+"','"+txtapellido.getText()+"',"+Integer.parseInt(txtcurso.getText())+","+Integer.parseInt(txttitulacion.getText())+")");
            try
            {
                cnn=new conexion();
                sentenciaSQL=cnn.Conectarse().createStatement();
                String sql="SELECT * FROM clientes WHERE cliente="+Busqueda.getValueAt(fila,0);
                rs=sentenciaSQL.executeQuery(sql);
                rs.next();
                
                //aux=new datosc();
                
                aux=new datosc(rs.getString("cliente"),rs.getString("nombre"),rs.getString("paterno"),
                    rs.getString("materno"),rs.getString("direccion"),rs.getString("telefono"));
                
                envia();
                //cl.numero.setText(aux.paterno());
                //cl.numero.setText(rs.getString("cliente"));
                //cl.show();
                rs.close();
                sentenciaSQL.close();
                cnn.CerrarConexion();
                
            }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } catch (InstantiationException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } catch (IllegalAccessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        }
    }//GEN-LAST:event_BusquedaMouseClicked

    private void articuloPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_articuloPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_articuloPropertyChange

    
    public void MostrarTabla(){
        String sql;
        try{
            cnn=new conexion();
            sentenciaSQL=cnn.Conectarse().createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
            sql="SELECT * FROM clientes";
            ResultSet rsth=sentenciaSQL.executeQuery(sql);
            ResultSetMetaData rsmd= rsth.getMetaData();
            int col=rsmd.getColumnCount();
            DefaultTableModel modelo= new DefaultTableModel();
            
            for(int i=1; i<=col; i++){
                //se rellena con encabezados de la tabla
                modelo.addColumn(rsmd.getColumnLabel(i));
            }
            while(rsth.next()){//se llena la tabla con registros
            String fila[]=new String[col];
            for(int j=0;j<col;j++){
                fila[j]=rsth.getString(j+1);
            }
            modelo.addRow(fila);
           }
            Busqueda.setModel(modelo);
            cnn.CerrarConexion();
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } catch (InstantiationException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } catch (IllegalAccessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cuentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Busqueda;
    public javax.swing.JTable articulo;
    private javax.swing.JTextField cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
