/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Datos;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.*;
/**
 *
 * @author java
 */
public class Ventas_Socios extends javax.swing.JFrame {

    /**
     * Creates new form Ventas
     */
    private Statement sentenciaSQL;
    private ResultSet rs;
    conexion cnn;
    
    Random rm=new Random();
    int ran=rm.nextInt(1000000);
    String ranc=Integer.toString(ran);
    
    public Ventas_Socios() {
        initComponents();
        jLabel12.setText(ranc);
        fecha();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        todos = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        apellido = new javax.swing.JTextField();
        articulo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        articulo2 = new javax.swing.JTextField();
        descripcion = new javax.swing.JTextField();
        area = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        precio1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        mes1 = new javax.swing.JRadioButton();
        mes2 = new javax.swing.JRadioButton();
        mes3 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        abono = new javax.swing.JTextField();
        Aceptar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        semana1 = new javax.swing.JRadioButton();
        semana2 = new javax.swing.JRadioButton();
        semana3 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        quincena1 = new javax.swing.JRadioButton();
        quincena2 = new javax.swing.JRadioButton();
        quincena3 = new javax.swing.JRadioButton();
        ir = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("No Cliente:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        jPanel1.add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 170, -1));

        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 210, -1));

        jLabel3.setText("Apellido:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel4.setText("Articulo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));
        jPanel1.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 210, -1));
        jPanel1.add(articulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 120, -1));

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("No Articulo:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel6.setText("Descripcion:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel7.setText("Area:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        jPanel2.add(articulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 140, -1));
        jPanel2.add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 140, -1));
        jPanel2.add(area, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 140, -1));

        jLabel8.setText("Precio Abonos:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
        jPanel2.add(precio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 140, -1));

        jPanel3.setBackground(new java.awt.Color(204, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        todos.add(mes1);
        mes1.setText("3 meses");
        mes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mes1ActionPerformed(evt);
            }
        });
        jPanel3.add(mes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        todos.add(mes2);
        mes2.setText("6 meses");
        mes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mes2ActionPerformed(evt);
            }
        });
        jPanel3.add(mes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        todos.add(mes3);
        mes3.setText("12 meses");
        mes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mes3ActionPerformed(evt);
            }
        });
        jPanel3.add(mes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 100, 140));

        jLabel9.setText("Abono Fijo de:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));
        jPanel2.add(abono, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 90, -1));

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        jPanel2.add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        jLabel13.setText("Seleccione el Plazo:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jPanel4.setBackground(new java.awt.Color(204, 255, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        todos.add(semana1);
        semana1.setText("12 semanas");
        semana1.setEnabled(false);
        semana1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semana1ActionPerformed(evt);
            }
        });
        jPanel4.add(semana1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        todos.add(semana2);
        semana2.setText("24 semanas");
        semana2.setEnabled(false);
        semana2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semana2ActionPerformed(evt);
            }
        });
        jPanel4.add(semana2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        todos.add(semana3);
        semana3.setText("48 semanas");
        semana3.setEnabled(false);
        semana3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semana3ActionPerformed(evt);
            }
        });
        jPanel4.add(semana3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 120, 130));

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        todos.add(quincena1);
        quincena1.setText("6 quincenas");
        quincena1.setEnabled(false);
        quincena1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quincena1ActionPerformed(evt);
            }
        });
        jPanel5.add(quincena1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        todos.add(quincena2);
        quincena2.setText("12 quincenas");
        quincena2.setEnabled(false);
        quincena2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quincena2ActionPerformed(evt);
            }
        });
        jPanel5.add(quincena2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        todos.add(quincena3);
        quincena3.setText("24 quincenas");
        quincena3.setEnabled(false);
        quincena3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quincena3ActionPerformed(evt);
            }
        });
        jPanel5.add(quincena3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 120, 110));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 570, 380));

        ir.setText("Ir");
        ir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irActionPerformed(evt);
            }
        });
        jPanel1.add(ir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 40, -1));

        jLabel10.setText("fecha:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, -1));

        jLabel11.setText("Venta No:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel12.setText("jLabel12");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("Venta Socios");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1000, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void fecha(){
        Calendar fecha=new GregorianCalendar();
        int año=fecha.get(Calendar.YEAR);
        int mes=fecha.get(Calendar.MONTH);
        int dia=fecha.get(Calendar.DAY_OF_MONTH);
        
        jLabel10.setText(" "+año+"/"+(mes+1)+"/"+dia);
    }
    public void validar(String articulo) throws ClassNotFoundException, InstantiationException, IllegalAccessException{
        try{
            cnn=new conexion();
            sentenciaSQL=cnn.Conectarse().createStatement();
            String consulta="SELECT * FROM articulos WHERE articulo = '" +articulo+"'";
            rs=sentenciaSQL.executeQuery(consulta);
            
            boolean ban1=false;
            boolean ban2=false;
            
            while(rs.next()){
                String nart=rs.getString("articulo");
 
                if(articulo.equals(nart)){
                  articulo2.setText(rs.getString("articulo"));
                  descripcion.setText(rs.getString("descripcion"));
                  area.setText(rs.getString("area"));
                  precio1.setText(rs.getString("precioA"));
                  ban2=true;
                  break;
                }
            }
            if(ban2==false){
                JOptionPane.showMessageDialog(null, "no se encuentra el articulo");
            }
           rs.close();
           sentenciaSQL.close();
           cnn.CerrarConexion();
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void irActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irActionPerformed
        try {
            // TODO add your handling code here:
            validar(articulo.getText());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ventas_Socios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Ventas_Socios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Ventas_Socios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_irActionPerformed

    public String plazo="";
    private void mes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mes1ActionPerformed
        // TODO add your handling code here:
        int res=0;
        
        res=(Integer.parseInt(precio1.getText())/3);
        
        abono.setText(Integer.toString(res));
        
        semana1.setEnabled(true);
        semana2.setEnabled(false);
        semana3.setEnabled(false);
        
        quincena1.setEnabled(true);
        quincena2.setEnabled(false);
        quincena3.setEnabled(false);
        
        plazo="3 meses";
    }//GEN-LAST:event_mes1ActionPerformed

    private void mes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mes2ActionPerformed
        // TODO add your handling code here:
        int res=0;
        
        res=(Integer.parseInt(precio1.getText())/6);
        
        abono.setText(Integer.toString(res));
        
        semana1.setEnabled(false);
        semana2.setEnabled(true);
        semana3.setEnabled(false);
        
        quincena1.setEnabled(false);
        quincena2.setEnabled(true);
        quincena3.setEnabled(false);
        
        plazo="6 meses";
    }//GEN-LAST:event_mes2ActionPerformed

    private void mes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mes3ActionPerformed
        // TODO add your handling code here:
        int res=0;
        
        res=(Integer.parseInt(precio1.getText())/12);
        
        abono.setText(Integer.toString(res));
        
        semana1.setEnabled(false);
        semana2.setEnabled(false);
        semana3.setEnabled(true);
        
        quincena1.setEnabled(false);
        quincena2.setEnabled(false);
        quincena3.setEnabled(true);
        
        plazo="12 meses";
    }//GEN-LAST:event_mes3ActionPerformed

    private void semana1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semana1ActionPerformed
        // TODO add your handling code here:
        int res=0;
        
        res=(Integer.parseInt(precio1.getText())/12);
        
        abono.setText(Integer.toString(res));
        
        plazo="12 semanas";
    }//GEN-LAST:event_semana1ActionPerformed

    private void semana2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semana2ActionPerformed
        // TODO add your handling code here:
        int res=0;
        
        res=(Integer.parseInt(precio1.getText())/24);
        
        abono.setText(Integer.toString(res));
        
        plazo="24 semanas";
    }//GEN-LAST:event_semana2ActionPerformed

    private void semana3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semana3ActionPerformed
        // TODO add your handling code here:
        int res=0;
        
        res=(Integer.parseInt(precio1.getText())/48);
        
        abono.setText(Integer.toString(res));
        
        plazo="48 semanas";
    }//GEN-LAST:event_semana3ActionPerformed

    private void quincena1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quincena1ActionPerformed
        // TODO add your handling code here:
        int res=0;
        
        res=(Integer.parseInt(precio1.getText())/6);
        
        abono.setText(Integer.toString(res));
        
        plazo="6 quincenas";
    }//GEN-LAST:event_quincena1ActionPerformed

    private void quincena2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quincena2ActionPerformed
        // TODO add your handling code here:
        int res=0;
        
        res=(Integer.parseInt(precio1.getText())/12);
        
        abono.setText(Integer.toString(res));
        
        plazo="12 quincenas";
    }//GEN-LAST:event_quincena2ActionPerformed

    private void quincena3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quincena3ActionPerformed
        // TODO add your handling code here:
        int res=0;
        
        res=(Integer.parseInt(precio1.getText())/24);
        
        abono.setText(Integer.toString(res));
        
        plazo="24 quincenas";
    }//GEN-LAST:event_quincena3ActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        
        try{
            cnn=new conexion();
            sentenciaSQL=cnn.Conectarse().createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
            sentenciaSQL.executeUpdate("INSERT INTO creditos (venta,cliente,nombre,apellido,articulo,precioA,plazo,abono,fecha) VALUES ("+Integer.parseInt(jLabel12.getText())
                    +","+Integer.parseInt(cliente.getText())+",'"+nombre.getText()+"','"+apellido.getText()+"',"+Integer.parseInt(articulo2.getText())+","
                    +Integer.parseInt(precio1.getText())+",'"+plazo+"',"+Integer.parseInt(abono.getText())+",'"+jLabel10.getText()+"')");
            
            
            sentenciaSQL.executeUpdate("insert into abonos(id,nombre,apellido,descripcion,costo,sugerido,abono,saldo,fecha)values("+Integer.parseInt(cliente.getText())
                    +",'"+nombre.getText()+"','"+apellido.getText()+"','"+descripcion.getText()+"',"+Integer.parseInt(precio1.getText())
                    +","+Integer.parseInt(abono.getText())+","+Integer.parseInt("0")+","+Integer.parseInt(precio1.getText())+",'"+jLabel10.getText()+"')");
            
            JOptionPane.showMessageDialog(null, "se ha realizado una venta a credito: ");
            sentenciaSQL.close();
            cnn.CerrarConexion();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } catch (InstantiationException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } catch (IllegalAccessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_AceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas_Socios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas_Socios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas_Socios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas_Socios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas_Socios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JTextField abono;
    public javax.swing.JTextField apellido;
    private javax.swing.JTextField area;
    private javax.swing.JTextField articulo;
    private javax.swing.JTextField articulo2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    public javax.swing.JTextField cliente;
    private javax.swing.JTextField descripcion;
    private javax.swing.JButton ir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton mes1;
    private javax.swing.JRadioButton mes2;
    private javax.swing.JRadioButton mes3;
    public javax.swing.JTextField nombre;
    private javax.swing.JTextField precio1;
    private javax.swing.JRadioButton quincena1;
    private javax.swing.JRadioButton quincena2;
    private javax.swing.JRadioButton quincena3;
    private javax.swing.JRadioButton semana1;
    private javax.swing.JRadioButton semana2;
    private javax.swing.JRadioButton semana3;
    private javax.swing.ButtonGroup todos;
    // End of variables declaration//GEN-END:variables
}
