/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Datos;

import java.awt.TextField;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author java
 */
public class Ventas extends javax.swing.JFrame {

    /**
     * Creates new form Ventas
     */
    
    DefaultTableModel tablatmp;
    
    private Statement sentenciaSQL;
    private ResultSet rs;
    conexion cnn;
    
    Random rm=new Random();
    int ran=rm.nextInt(1000000);
    String ranc=Integer.toString(ran);

    public Ventas() {
        initComponents();
        jLabel6.setText(ranc);
        
        tablatmp = (DefaultTableModel) temporal.getModel();

        tablatmp.addColumn("articulo");
        tablatmp.addColumn("descripcion");
        tablatmp.addColumn("precio");
        tablatmp.addColumn("cantidad");
        
        temporal.setModel(tablatmp);
        
        fecha();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        articulo1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        temporal = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        ticket = new javax.swing.JRadioButton();
        factura = new javax.swing.JRadioButton();
        terminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        apellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel2.setText("Articulos:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 160, -1));
        jPanel1.add(articulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 160, -1));

        temporal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(temporal);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 670, 190));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(ticket);
        ticket.setText("Ticket");
        ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketActionPerformed(evt);
            }
        });
        jPanel2.add(ticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        buttonGroup1.add(factura);
        factura.setText("Factura");
        factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturaActionPerformed(evt);
            }
        });
        jPanel2.add(factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 100, 150));

        terminar.setText("Terminar");
        terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminarActionPerformed(evt);
            }
        });
        jPanel1.add(terminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jLabel3.setText("Apeliido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        jPanel1.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 160, -1));

        jLabel4.setText("fecha:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        jLabel5.setText("Venta No:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel7.setText("cantidad");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));
        jPanel1.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 110, -1));

        jLabel8.setText("precio:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        jPanel1.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 130, -1));

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        jPanel1.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Crear Venta");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 690, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void fecha(){
        Calendar fecha=new GregorianCalendar();
        int año=fecha.get(Calendar.YEAR);
        int mes=fecha.get(Calendar.MONTH);
        int dia=fecha.get(Calendar.DAY_OF_MONTH);
        
        jLabel4.setText(" "+año+"/"+(mes+1)+"/"+dia);
    }
    
    public void validar(String articulo) throws ClassNotFoundException, InstantiationException, IllegalAccessException{
        try{
            cnn=new conexion();
            sentenciaSQL=cnn.Conectarse().createStatement();
            String consulta="SELECT * FROM articulos WHERE articulo = '" +articulo+"'";
            rs=sentenciaSQL.executeQuery(consulta);
            
            boolean ban1=false;
            boolean ban2=false;
            
            TextField txt=new TextField();
            
            while(rs.next()){
                String nart=rs.getString("articulo");
 
                if(articulo.equals(nart)){
                    precio.setText(rs.getString("precioC"));
                    txt.setText(rs.getString("descripcion"));
                    String[] arr=new String[4];
                    
                    arr[0]=articulo1.getText();
                    arr[1]=txt.getText();
                    arr[2]=precio.getText();
                    arr[3]=cantidad.getText();
                    
                   tablatmp= (DefaultTableModel) temporal.getModel();
                   tablatmp.addRow(arr);
                  ban2=true;
                  break;
                }
            }
            if(ban2==false){
                JOptionPane.showMessageDialog(null, "no se encuentra el articulo");
            }
           rs.close();
           sentenciaSQL.close();
           cnn.CerrarConexion();
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        try {
            // TODO add your handling code here:
            validar(articulo1.getText());
            nombre.setEnabled(false);
            apellido.setEnabled(false);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_aceptarActionPerformed

            
    String articulo;
    String descripcion;
    String precio1;
    String cantidad1;
            
    int fila;
    int columna;
    private void terminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminarActionPerformed
        // TODO add your handling code here:
        //tablatmp

        if(temporal.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"no es posible que la tabla este vacia");
        }else{
            fila=tablatmp.getRowCount();
            columna=tablatmp.getColumnCount();
            
        for(int i=0;i<fila;i++){
            articulo=temporal.getValueAt(i, 0).toString();
            descripcion=temporal.getValueAt(i, 1).toString();
            precio1=temporal.getValueAt(i, 2).toString();
            cantidad1=temporal.getValueAt(i, 3).toString();
        }//fin del for
        
        try{
            cnn=new conexion();
            sentenciaSQL=cnn.Conectarse().createStatement();
            sentenciaSQL.executeUpdate("insert into ventas(venta,nombre,paterno,articulo,descripcion,pago,precio,cantidad,fecha) values("
                    +Integer.parseInt(jLabel6.getText())+",'"+nombre.getText()+"','"+apellido.getText()+"','"+articulo+"','"+descripcion+"','"+pago+"','"+precio1+"','"+cantidad1+"','"+jLabel4.getText()+"')");
            sentenciaSQL.close();
            cnn.CerrarConexion();
            }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
            Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
            Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }//fin del else
        JOptionPane.showMessageDialog(null,"venta registrada imprima el ticket");
    }//GEN-LAST:event_terminarActionPerformed

    String pago="";
    private void ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketActionPerformed
        // TODO add your handling code here:
        pago="ticket";
    }//GEN-LAST:event_ticketActionPerformed

    private void facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturaActionPerformed
        // TODO add your handling code here:
        pago="factura";
    }//GEN-LAST:event_facturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField apellido;
    private javax.swing.JTextField articulo1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cantidad;
    private javax.swing.JRadioButton factura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField precio;
    private javax.swing.JTable temporal;
    private javax.swing.JButton terminar;
    private javax.swing.JRadioButton ticket;
    // End of variables declaration//GEN-END:variables
}
